### ISSUE TITLE
hyper parameters

### ISSUE THREAD

**Issue by phoenixsecularbird** [jugechengzi/FR#1]
Could you please provide the hyper parameters you used for the other aspects? I have successfully achieved your reported performance on aspect 0 of beer view, but I failed on aspect 1 (see the screenshot). Thanks a lot!

![image](https://user-images.githubusercontent.com/49329979/192988260-615f8fdf-386d-46e4-ae71-b7506e44c954.png)

**Comment by jugechengzi** [comment]
The sparsity is too high. Different aspects use different sparsity (e.g., 0.14 for beer aspect 1). See our appendix.

**Comment by phoenixsecularbird** [comment]
But I  cannot get it. Do you mean Table 8 in appendix?

**Comment by jugechengzi** [comment]
Yes, set the sparsity_percentage to 0.14 for beer 1.

**Comment by jugechengzi** [comment]
Have you successfully reproduced the results?

**Comment by phoenixsecularbird** [comment]
I am sorry but I cannot. The results of beer 1 with  sparsity_percentage as 0.14 are as follows:

![image](https://user-images.githubusercontent.com/49329979/193444769-f0da5421-d84e-4f03-9b5e-68f8af871941.png)


![image](https://user-images.githubusercontent.com/49329979/193444749-d35fa4f6-4367-41f7-8518-f4236c97685c.png)

**Comment by jugechengzi** [comment]
Try this:  python run_share_beer.py --lr 0.0001 --batch_size 256 --share 1 --sparsity_percentage 0.123 --sparsity_lambda 12 --continuity_lambda 10 --epochs 400.  We refer to the implementation of DMR and the sparsity is loosely limited. Usually the preset s should be smaller than the final sparsity. More questions please contact idc_lw@hust.edu.cn.

**Comment by phoenixsecularbird** [comment]
OK. I will have a try.

**Comment by phoenixsecularbird** [comment]
I have obtained similar results as you reported. Thanks a lot! It seems that more training epochs are essential.

**Comment by jugechengzi** [comment]
Other hyper-parameters have been uploaded.
