### ISSUE TITLE
About skewed-generator

### ISSUE THREAD

**Issue by shuaibo919** [jugechengzi/FR#2]
Hi, sorry to bother you. I'm not sure how the Skewed generator is pre-trained. My understanding is as follows:

1. When pre-training the generator, the regularizer of shortness and coherence is kept, while selecting the first token or not to represent the prediction.

2. There are no restrictions on the generator's choice when selecting the first token or not to represent the prediction.

1 right or 2 right, or neither？

 And could you tell me more about how to set up the experimental details for the Skewed generator?

Thank you!

**Comment by jugechengzi** [comment]
Hi, I have updated some tips on how to understand our code and build your own method on top of it. I think they might help you.

Here are the answers to your question:  
The second one is what we do, but you can also try the first one as long as you want. I think your suggestion is good, and the first one might be better. However, we do the second in our paper.  
 You can find the function "train_g_skew" in train_util.py. And you can find the "g_skew" function in "GenEncShareModel". These are the two core functions we used for the skewed generator.  

Please let me know if you have any further questions or succeed in doing so.

**Comment by shuaibo919** [comment]
Thank you for your reply! I think I understand the details now. Have a great weekend!(蟹蟹！👍）

**Comment by jugechengzi** [comment]
I also suggest that you read our latest papers. DR gives a deeper insight into the degeneration problem studied in FR. And MGR tries to tackle a different problem. Both DR and MGR perform better than FR. However, FR is the simplest and most flexible method and can be easily combined with many existing methods.

**Comment by shuaibo919** [comment]
Hi there! I just wanted to let you know that I've read through all three of your articles and found them very inspiring. I've also starred all three repositories and referenced your articles in my work(hope my article will be published successfully 😭 ).
Thanks again for your sharing!
